name = "GamersRefined"
author = "GamersModpacks"
version = "v4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce760370473ba2d1b4a04840b3a8647798bdef6086305074d5d48e9dafd33671"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
