name = "GamersRefined"
author = "GamersModpacks"
version = "v.1.4-pre"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eb478a55e95bb008cf8dc1458c647eee54ed0b2f796f580eda4a4858644b2ca"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
