name = "GamersRefined"
author = "GamersModpacks"
version = "v4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1c094aafed5c5942b419656c93298d7c75c23cb9ddc8d6f6ca2aeac552ed340"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
