name = "GamersRefined"
author = "GamersModpacks"
version = "v5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab03e8e3f8c66b5f14a820a21b8a1ffec1009aceb17e2a869596d819dc718703"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
