name = "GamersRefined"
author = "GamersModpacks"
version = "v.1.4-pre"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e04479218da02b1473a03be6f10c3783e87690d743ee3193739572e79cc2a37f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
