name = "GamersRefined"
author = "GamersModpacks"
version = "v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffa8d3b7ac87095d4229607aab47f5b4938cf85e7bfa395888e0564983d790b1"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
