name = "GamersRefined"
author = "GamersModpacks"
version = "v1.3.4-pre"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbe8066d6a1b06b1bef9b4b18584479c543b5b0fad080b676e0a7dbfd843c3bc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
