name = "GamersRefined"
author = "GamersModpacks"
version = "v1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b1ed45335bc206736def7fa16ab87047e7f5fa9ee57ef8c1d3ce254df4e632d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
