name = "GamersRefined"
author = "GamersModpacks"
version = "v4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bbf380a9c57b54775c6430a4619ea7f0f53889b909bc795dbea8202f712c3c8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
