hash-format = "sha256"

[[files]]
file = "config/openloader/advanced_options.json"

[[files]]
file = "config/openloader/resources/fresh-animations.pw.toml"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
metafile = true

[[files]]
file = "mods/iris-flw-compat.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true
