hash-format = "sha256"

[[files]]
file = "config/openloader/resources/create-immersive-aircrafts-resource-pack.pw.toml"
metafile = true

[[files]]
file = "config/openloader/resources/fresh-animations.pw.toml"
metafile = true

[[files]]
file = "mods/iris-flw-compat.pw.toml"
metafile = true
