name = "GamersRefined"
author = "GamersModpacks"
version = "v3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f66e0474aafe223b363250e91e8a73402d221d7be0f3bcf7c3bf11912eeb131f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
