name = "GamersRefined"
author = "GamersModpacks"
version = "v1.3-pre"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d06e8da6c5aab55363135d951373acf1925a571c830ec622e8d0211a402e9eae"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
