name = "GamersRefined"
author = "GamersModpacks"
version = "v1.3.5-pre"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27d0dc7a1c9519b5628786b92d9783db2f472de778cd2142134b7f4654368b16"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
