hash-format = "sha256"

[[files]]
file = "config/bclib/client.json"

[[files]]
file = "config/create-client.toml"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/fancymenu/assets/background.jpg"

[[files]]
file = "config/fancymenu/assets/logo.png"

[[files]]
file = "config/fancymenu/options.txt"

[[files]]
file = "filesToRemove.txt"
