hash-format = "sha256"

[[files]]
file = "config/bclib/client.json"

[[files]]
file = "config/create-client.toml"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/fancymenu/assets/background.jpg"

[[files]]
file = "config/fancymenu/assets/icon.icns"

[[files]]
file = "config/fancymenu/assets/icon16.png"

[[files]]
file = "config/fancymenu/assets/icon32.png"

[[files]]
file = "config/fancymenu/assets/logo.png"

[[files]]
file = "config/fancymenu/options.txt"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "filesToRemove.txt"

[[files]]
file = "mods/emi-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/way2wayfabric.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true
