name = "GamersRefined"
author = "GamersModpacks"
version = "v5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b420612e7e51dae2ace863d919edf8c79f2b3c76ffc85dede53e0015b4e2810"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
