name = "GamersRefined"
author = "GamersModpacks"
version = "v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c086cc2c19c39cffea390175cc26b1a27a99c0df3ab5a8ef8a336ff0d9f10f0e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
no-internal-hashes = "true"
